// ── PendingOrderOverlay — limit/stop/stop-limit pending order marker ──
// Displays a dashed horizontal line at the order price with a coloured
// label showing order type + side (e.g. 'BUY LIMIT', 'SELL STOP').
//
// Data shape:
//   { orderType: 'limit' | 'stop' | 'stop-limit',
//     side: 'buy' | 'sell',
//     status: 'pending' | 'partially-filled',
//     label?: string (auto-generated by service if omitted) }
//
// Style: color is set by the runtime service based on side,
//        lineDash reflects pending status (dashed = pending).
//
// @since 3.3.8

import { createPriceLineOverlay } from '../../PriceLineOverlayBase'

// The runtime service sets data.label and data.style.color per-instance.
// Base defaults serve as fallback only.
export const pendingOrderDefinition = createPriceLineOverlay({
  id: 'pending-order',
  name: 'Pending Order',
  category: 'trade',
  defaultStyle: {
    color: '#42a5f5',
    lineWidth: 1.5,
    lineDash: [6, 3],
    labelBg: '#42a5f5',
    labelText: '#ffffff',
    icon: '\u{1F4DD}', // 📝
  },
})
