/**
 * ReportPanel.tsx — Thin React host for ReportRuntime
 *
 * Thin wrapper that displays report views (backtest, optimization).
 * No business logic — pure view layer.
 *
 * @since 3.7.2
 */

import { useEffect, useState, useRef, type ReactNode } from 'react'
import { ReportRuntime } from '../../reports/runtime/ReportRuntime'
import type { ReportView, ReportSources, SectionView } from '../../reports/types'

export interface ReportPanelProps {
  /** Report sources from a backtest session */
  sources?: ReportSources
  /** Report name */
  name?: string
}

/** Render a section view to React elements */
function renderSection(section: SectionView, index: number): ReactNode {
  const label: Record<string, string> = {
    summary: 'Summary Metrics',
    equity: 'Equity & Drawdown',
    risk: 'Risk Metrics',
    trades: 'Trade Analytics',
    optimization: 'Optimization Results',
    parameters: 'Parameters',
  }

  const title: string = label[section.type] ?? section.type

  return (
    <div key={`${section.type}-${index}`} style={{ marginBottom: 16 }}>
      <div style={{ color: '#7ee787', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>
        {title}
      </div>
      <div style={{ paddingLeft: 12, color: '#8b949e', fontSize: 11 }}>
        {section.type === 'summary' && (
          <>
            <div>Net Profit: {section.data.netProfit?.toFixed(2) ?? '—'}</div>
            <div>Sharpe: {section.data.sharpe?.toFixed(3) ?? '—'}</div>
            <div>Max DD: {section.data.maxDrawdown?.toFixed(3) ?? '—'}</div>
            <div>Win Rate: {section.data.winRate?.toFixed(2) ?? '—'}%</div>
            <div>Trades: {section.data.totalTrades}</div>
          </>
        )}
        {section.type === 'risk' && (
          <>
            <div>Recovery Factor: {section.data.recoveryFactor?.toFixed(3) ?? '—'}</div>
            <div>Calmar Ratio: {section.data.calmarRatio?.toFixed(3) ?? '—'}</div>
            <div>Kelly: {section.data.kellyCriterion?.toFixed(3) ?? '—'}</div>
            <div>SQN: {section.data.sqn?.toFixed(3) ?? '—'}</div>
          </>
        )}
        {section.type === 'equity' && (
          <div>Equity points: {section.data.equityCurve.length}</div>
        )}
        {section.type === 'trades' && (
          <div>Trade records: {section.data.tradeList.length}</div>
        )}
        {section.type === 'optimization' && (
          <div>Trials: {section.data.leaderboard.length}</div>
        )}
        {section.type === 'parameters' && (
          <div>{Object.keys(section.data).length} params</div>
        )}
      </div>
    </div>
  )
}

/**
 * ReportPanel — displays a report view generated by ReportRuntime.
 * Thin view layer — no business logic.
 */
export function ReportPanel({ sources, name = 'Backtest Report' }: ReportPanelProps): ReactNode {
  const [report, setReport] = useState<ReportView | null>(null)
  const runtimeRef = useRef<ReportRuntime>(new ReportRuntime())

  useEffect(() => {
    if (!sources) {
      setReport(null)
      return
    }
    const r = runtimeRef.current.buildDefaultReport(name, sources)
    setReport(r)
  }, [sources, name])

  if (!report) {
    return (
      <div style={{
        padding: 16,
        color: '#8b949e',
        fontFamily: 'monospace',
        fontSize: 13,
        height: '100%',
        background: '#0d1117',
        overflow: 'auto',
      }}>
        <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 12, color: '#58a6ff' }}>
          Reports
        </div>
        <div style={{ color: '#484f58', fontStyle: 'italic' }}>
          No report data. Run a backtest to generate a report.
        </div>
      </div>
    )
  }

  return (
    <div style={{
      padding: 16,
      color: '#c9d1d9',
      fontFamily: 'monospace',
      fontSize: 13,
      height: '100%',
      background: '#0d1117',
      overflow: 'auto',
    }}>
      <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 12, color: '#58a6ff' }}>
        {report.name}
      </div>
      <div style={{ color: '#8b949e', fontSize: 11, marginBottom: 12 }}>
        Generated: {new Date(report.generatedAt).toISOString()} | Sections: {report.sections.length}
      </div>
      <div style={{ borderTop: '1px solid #21262d', margin: '12px 0' }} />
      {report.sections.map((section, i) => renderSection(section, i))}
    </div>
  )
}
